apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: mario-backend
type: Opaque
data:
  POSTGRES_DB: c3VwZXJtYXJpbw== # "supermario"
  POSTGRES_USER: c3VwZXJ1c2Vy # "superuser"
  POSTGRES_PASSWORD: c3VwZXJwYXNz # "superpass"
