apiVersion: v1
kind: Secret
metadata:
  name: db-conn
  namespace: mario-backend
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL3N1cGVydXNlcjpzdXBlcnBhc3NAZGIubWFyaW8tYmFja2VuZC5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3N1cGVybWFyaW8=
  # value (base64): postgresql://superuser:superpass@db.mario-backend.svc.cluster.local:5432/supermario
