# values for monitoring-extras (no kube-prometheus-stack keys here)
enabled: true

# where the ingress controller runs
ingressNginxNamespace: ingress-nginx
ingressMetricsPort: 10254

# must match the Helm release name & namespace used by the Argo CD app
promStackRelease: monitoring
promStackNamespace: monitoring
