{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-metrics
  namespace: {{ .Values.ingressNginxNamespace }}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
  ports:
    - name: metrics
      port: {{ .Values.ingressMetricsPort }}
      targetPort: {{ .Values.ingressMetricsPort }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx
  namespace: {{ .Values.promStackNamespace }}
  labels:
    # This label MUST equal the Helm release name of kube-prometheus-stack
    release: {{ .Values.promStackRelease | quote }}
spec:
  namespaceSelector:
    matchNames: [{{ .Values.ingressNginxNamespace | quote }}]
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
  endpoints:
    - port: metrics
      interval: 30s
{{- end }}
