apiVersion: v1
kind: ConfigMap
metadata:
  name: web-nginx
data:
  nginx.conf: |
    worker_processes  1;
    events { worker_connections 1024; }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile      on;
      keepalive_timeout  65;

      upstream backend {
        server app-svc.mario-backend.svc.cluster.local:8000;
      }

      server {
        listen 80;
        root /usr/share/nginx/html;   # <-- moved here so /images uses it too
        index index.html;

        # list the images directory (avoids 403 on /images/)
        location /images/ {
          autoindex on;
          autoindex_exact_size off;
          autoindex_localtime on;
          try_files $uri $uri/ =404;
        }

        # SPA static files
        location / {
          try_files $uri $uri/ /index.html;
        }

        # health for k8s probes
        location = /health {
          add_header Content-Type application/json;
          return 200 '{"status":"ok"}';
        }

        # proxy API to backend
        location /api/ {
          proxy_pass http://backend;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Connection "";
        }
      }
    }
