apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
  labels:
    app: mario-web
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: mario-web
  template:
    metadata:
      labels:
        app: mario-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port | default 80 }}

          # --- health checks ---
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port | default 80 }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port | default 80 }}
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3

          # --- optional env from values ---
          {{- with .Values.env }}
          env:
{{ toYaml . | nindent 12 }}
          {{- end }}

          # --- optional resources from values ---
          {{- with .Values.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}

          # --- mount nginx config provided by ConfigMap ---
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true

      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Values.nginx.configMapName | default "web-nginx" }}
