apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: mario-web
spec:
  replicas: 1
  selector:
    matchLabels: { app: mario-web }
  template:
    metadata:
      labels: { app: mario-web }
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: 80, name: http }]
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
          {{- toYaml (default (dict
                "requests" (dict "cpu" "100m"  "memory" "128Mi")
                "limits"   (dict "cpu" "500m" "memory" "256Mi"))
                .Values.resources) | nindent 10 }}
