# devops-project1/infra/helm/web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
  labels:
    app: mario-web
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: mario-web
  template:
    metadata:
      labels:
        app: mario-web
      annotations:
        # roll pods when config changes
        checksum/nginx: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port | default 80 }}

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port | default 80 }}
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port | default 80 }}
            initialDelaySeconds: 3
            periodSeconds: 5

          {{- with .Values.env }}
          env:
{{ toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: web-nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true

      volumes:
        - name: web-nginx
          configMap:
            name: {{ .Values.nginx.configMapName | default "web-nginx" }}
