{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  labels: { app: mario-web }
  {{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      {{- $svcName := (default "web-svc" .Values.service.name) -}}
      {{- $svcPort := (default 80 .Values.service.port) -}}
      {{- range .Values.ingress.paths }}
      - path: {{ .path | default "/" }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ $svcName }}
            port:
              number: {{ .servicePort | default $svcPort }}
      {{- end }}
{{- end }}
