{{- $ing := (get .Values "ingress" | default (dict)) -}}
{{- if (get $ing "enabled" | default false) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: {{ get $ing "host" | default "web.mario.local" }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-svc
            port:
              number: {{ .Values.service.port | default 80 }}
{{- end }}
