{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName | default "nginx" | quote }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" | quote }}
  rules:
  - host: {{ required "ingress.host is required" .Values.ingress.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.path | default "/" | quote }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name | default "web-svc" | quote }}
            port:
              number: {{ .Values.service.port | default 80 }}
{{- end }}
