image:
  repository: docker.io/itaef/supermario-service
  tag: ""                       # chart will use .Chart.AppVersion
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: api.mario.local
  useRegex: false

secrets:
  createDbCreds: true
  createDbConn: true
  dbCreds:
    POSTGRES_DB: mario
    POSTGRES_USER: mario
    POSTGRES_PASSWORD: mario123


dbConn:
  url: "postgres://mario:mario123@db:5432/mario"

db:
  enabled: true
  storage:
    size: 1Gi
  storageClassName: standard
  service:
    name: db
    port: 5432
