image:
  repository: docker.io/itaef/supermario-service
  tag: ""                    # ← empty means “use .Chart.AppVersion”
  pullPolicy: IfNotPresent

service:
  port: 8000

ingress:
  enabled: true
  host: api.mario.local
  useRegex: false

secrets:
  # prevent Argo “RepeatedResourceWarning” by default
  createDbConn: false
  createDbCreds: false
  dbConn:
    url: ""                 # set only if createDbConn=true
  dbCreds:
    POSTGRES_DB: ""
    POSTGRES_USER: ""
    POSTGRES_PASSWORD: ""

autoscaling:
  mode: none                # one of: none | hpa | keda
  hpa:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  keda:
    minReplicaCount: 1
    maxReplicaCount: 3
    # add your KEDA triggers here
