# /devops-project1/infra/helm/backend/values.yaml
image:
  repository: docker.io/itaef/supermario-service
  tag: ""                    # ← empty means “use .Chart.AppVersion”
  pullPolicy: IfNotPresent

# Make every resource name resolve to "app"
fullnameOverride: "app"

service:
  port: 8000

ingress:
  enabled: true
  host: api.mario.local
  useRegex: false

secrets:
  # prevent Argo “RepeatedResourceWarning” by default
  createDbConn: true
  createDbCreds: true
  dbConn:
    url: ""                 # set only if createDbConn=true
  dbCreds:
    POSTGRES_DB: mario
    POSTGRES_USER: mario
    POSTGRES_PASSWORD: mario123

runtime:
  fixPasswd: false  # set true only if you still need the passwd overlay

autoscaling:
  mode: none                # one of: none | hpa | keda

  hpa:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

  keda:
    minReplicaCount: 1
    maxReplicaCount: 3
# optional auths (empty is fine)
    auths: []

    # at least one ScaledObject to see KEDA resources
    scaledObjects:
      - name: http-queue
        minReplicaCount: 1
        maxReplicaCount: 3
        triggers:
          - type: prometheus
            metadata:
              serverAddress: http://prometheus-operated.monitoring.svc:9090
              metricName: http_requests_pending
              threshold: "100"
              query: sum(rate(http_requests_pending[1m]))

db:
  enabled: true
  image: postgres:15
  storage:
    size: 1Gi
  service: { name: db, port: 5432 }
  secrets: { credsName: db-secrets }

