image:
  repository: docker.io/itaef/supermario-service
  tag: ""                    # ← empty means “use .Chart.AppVersion”
  pullPolicy: IfNotPresent

service:
  port: 8000

ingress:
  enabled: true
  host: api.mario.local
  useRegex: false

secrets:
  # prevent Argo “RepeatedResourceWarning” by default
  createDbConn: true
  createDbCreds: true
  dbConn:
    url: ""                 # set only if createDbConn=true
  dbCreds:
    POSTGRES_DB: mario
    POSTGRES_USER: mario
    POSTGRES_PASSWORD: mario123

runtime:
  fixPasswd: false  # set true only if you still need the passwd overlay

autoscaling:
  mode: none                # one of: none | hpa | keda
  fullnameOverride: "app"
  hpa:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  keda:
    minReplicaCount: 1
    maxReplicaCount: 3
    # add your KEDA triggers here

db:
  enabled: true
  image: postgres:15
  storage:
    size: 1Gi
  service: { name: db, port: 5432 }
  secrets: { credsName: db-secrets }

