apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd-apps
spec:
  project: default
  source:
    repoURL: https://github.com/tAIness/devops-project1.git
    targetRevision: HEAD
    path: infra/helm/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
