apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web
  namespace: argocd-apps
spec:
  project: default
  source:
    repoURL: https://github.com/tAIness/devops-project1.git
    targetRevision: HEAD
    path: infra/helm/web
    helm:
      valueFiles:
        - values.yaml   # create if you need overrides
  destination:
    server: https://kubernetes.default.svc
    namespace: web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
