# root-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default                 # use the same project name you render in project.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/tAIness/devops-project1.git
    targetRevision: main
    path: infra/helm/argocd-apps  # ← points to your chart folder
    helm: {}                      # (optional) valueFiles: [...] if you use non-defaults
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
