services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - supermario_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: ../app
    image: ${IMAGE_REPO_APP}:${TAG}
    environment:
      # inside the docker network postgres listens on 5432, not ${DB_PORT}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      PORT: "${FLASK_PORT}"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"

  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    image: ${IMAGE_REPO_WEB}:${TAG}
    ports: ["8081:80"]
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ../content/images:/usr/share/nginx/html/images:ro

volumes:
  supermario_db_data:
