services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - supermario_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    image: ${IMAGE_REPO_APP}:${TAG}
    environment:
      # IMPORTANT: inside compose network Postgres is always on 5432
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      PORT: "${FLASK_PORT:-8000}"     # <- use FLASK_PORT, default 8000 if missing
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"

  web:
    image: ${IMAGE_REPO_WEB}:${TAG}
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./content/images:/usr/share/nginx/html/images:ro

volumes:
  supermario_db_data:
    name: supermario_db_data           # <— fixed global name
    external: true                     # <— don’t let Compose delete/recreate it
