apiVersion: v1
kind: ConfigMap
metadata:
  name: web-nginx
  namespace: mario-web
data:
  nginx.conf: |
    user  nginx;
    worker_processes auto;
    events { worker_connections 1024; }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile      on;
      resolver 127.0.0.11 ipv6=off valid=30s;
      upstream app_upstream { server app-svc.mario-backend.svc.cluster.local:8000; }
      server {
        listen 80;
        server_name _;
        root  /usr/share/nginx/html;
        index index.html;
        location = / { try_files /index.html =404; }
        location /game/        { try_files $uri $uri/ =404; }
        location /leaderboard/ { try_files $uri $uri/ =404; }
        location = /scores     { return 308 /leaderboard/; }
        location = /scores/    { return 308 /leaderboard/; }
        location /assets/ { try_files $uri $uri/ =404; }
        location /css/    { try_files $uri $uri/ =404; }
        location /images/ { root /usr/share/nginx/html; autoindex on; autoindex_exact_size off; autoindex_localtime on; }
        location /api/ {
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          proxy_set_header Host              $host;
          proxy_set_header X-Real-IP         $remote_addr;
          proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://app_upstream;
        }
        location = /api/health { proxy_pass http://app_upstream/health; }
        location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico|webp)$ {
          try_files $uri =404;
          expires 7d;
          add_header Cache-Control "public, max-age=604800, immutable";
        }
        client_max_body_size 10m;
        add_header X-Content-Type-Options nosniff always;
        add_header X-Frame-Options SAMEORIGIN always;
        add_header Referrer-Policy no-referrer-when-downgrade always;
        add_header X-XSS-Protection "1; mode=block" always;
        proxy_read_timeout 30s; proxy_connect_timeout 5s; proxy_send_timeout 30s;
      }
    }
