# devops-project1/infra/helm/backend/templates/db-pvc.yaml
{{- /* infra/helm/backend/templates/db-pvc.yaml */ -}}
{{- $db := (.Values.db | default dict) -}}
{{- if ($db.enabled | default false) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: mario-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ (coalesce $db.storage.size "1Gi") | quote }}
{{- $sc := (coalesce $db.storage.storageClassName "") -}}
{{- if $sc }}
  storageClassName: {{ $sc | quote }}
{{- end }}
{{- end }}

