# devops-project1/infra/helm/backend/templates/db-pvc.yaml
{{- $db := (get .Values "db") | default (dict) -}}
{{- if (get $db "enabled" | default false) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
  namespace: {{ .Release.Namespace }}
  labels: { app: mario-db }
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.db.storage.size | default "1Gi" }}
{{- if .Values.db.storageClassName }}
  storageClassName: {{ .Values.db.storageClassName }}
{{- end }}
{{- end }}
