# devops-project1/infra/helm/backend/templates/hpa.yaml
{{- if eq (default "none" .Values.autoscaling.mode) "hpa" -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.fullnameOverride | default (printf "%s-%s" .Release.Name (.Chart.Name)) }}
  labels:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | default "backend" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.fullnameOverride | default (printf "%s-%s" .Release.Name (.Chart.Name)) }}
  minReplicas: {{ default 1 .Values.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ default 3 .Values.autoscaling.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ default 80 .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
{{- end -}}

