# devops-project1/infra/helm/backend/templates/hpa.yaml
{{- if eq (default "none" .Values.autoscaling.mode) "hpa" -}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  minReplicas: {{ .Values.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.fullnameOverride | default (printf "%s-%s" .Release.Name .Chart.Name) }}
{{- end }}
