# devops-project1/infra/helm/backend/templates/ingress.yaml
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.useRegex }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "{{ .Values.ingress.rewriteTarget | default "/$2" }}"
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
        {{- if .Values.ingress.useRegex }}
        # Regex mode: strip /api prefix, send /api/leaderboard -> /leaderboard
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: app-svc
              port:
                number: {{ .Values.service.port }}
        {{- else }}
        # Simple mode: forward /api/* as-is (no rewrite)
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: app-svc
              port:
                number: {{ .Values.service.port }}
        {{- end }}
        - path: /health
          pathType: Prefix
          backend:
            service:
              name: app-svc
              port:
                number: {{ .Values.service.port }}
{{- end }}
