# devops-project1/infra/helm/backend/templates/keda.yaml
{{- if eq (default "none" .Values.autoscaling.mode) "keda" -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.fullnameOverride | default "app" }}
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    name: {{ .Values.fullnameOverride | default "app" }}
  minReplicaCount: {{ .Values.autoscaling.keda.minReplicaCount | default 1 }}
  maxReplicaCount: {{ .Values.autoscaling.keda.maxReplicaCount | default 3 }}
  triggers:
{{ toYaml (default list .Values.autoscaling.keda.triggers) | nindent 4 }}
{{- end }}
