# devops-project1/infra/helm/backend/templates/keda.yaml
{{- if eq (default "none" .Values.autoscaling.mode) "keda" -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "backend.fullname" . | default "app" }}-http-queue
spec:
  scaleTargetRef:
    name: {{ include "backend.fullname" . | default "app" }}
  minReplicaCount: {{ .Values.autoscaling.keda.minReplicaCount | default 1 }}
  maxReplicaCount: {{ .Values.autoscaling.keda.maxReplicaCount | default 3 }}
  {{- with .Values.autoscaling.keda.triggers }}
  triggers:
{{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

