# devops-project1/infra/helm/backend/templates/keda.yaml
{{- if eq (default "none" .Values.autoscaling.mode) "keda" -}}
{{- $name := (.Values.fullnameOverride | default (printf "%s-%s" .Release.Name (.Chart.Name))) -}}
{{- $ns := .Release.Namespace -}}

{{- $keda := .Values.autoscaling.keda | default dict -}}
{{- $min := default 1 $keda.minReplicaCount -}}
{{- $max := default 3 $keda.maxReplicaCount -}}

{{- range $idx, $so := (default list $keda.scaledObjects) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ default (printf "%s-%d" $name $idx) $so.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $ns }}
spec:
  scaleTargetRef:
    name: {{ $name }}
  minReplicaCount: {{ default $min $so.minReplicaCount }}
  maxReplicaCount: {{ default $max $so.maxReplicaCount }}
  triggers:
{{ toYaml $so.triggers | indent 4 }}
---
{{- end }}
{{- end -}}
