# infra/helm/backend/templates/secret-db-conn.yaml
{{- if .Values.secrets.createDbConn }}
apiVersion: v1
kind: Secret
metadata:
  name: db-conn
type: Opaque
stringData:
  {{- /* prefer .Values.secrets.dbConn.url, fallback to .Values.dbConn.url */ -}}
  {{- $url := "" -}}
  {{- if and (kindIs "map" .Values.secrets) (kindIs "map" .Values.secrets.dbConn) -}}
    {{- $url = (.Values.secrets.dbConn.url | default "") -}}
  {{- end -}}
  {{- if and (eq $url "") (kindIs "map" .Values.dbConn) -}}
    {{- $url = (.Values.dbConn.url | default "") -}}
  {{- end -}}
  url: {{ required "either secrets.dbConn.url or dbConn.url must be set when createDbConn=true" $url | quote }}
{{- end }}
