  # templates/secret-db.yaml
  {{- if .Values.secrets.createDbCreds }}
  apiVersion: v1
  kind: Secret
  metadata:
    name: db-secrets
  type: Opaque
  stringData:
    POSTGRES_DB: "{{ .Values.secrets.dbCreds.POSTGRES_DB }}"
    POSTGRES_USER: "{{ .Values.secrets.dbCreds.POSTGRES_USER }}"
    POSTGRES_PASSWORD: "{{ .Values.secrets.dbCreds.POSTGRES_PASSWORD }}"
  {{- end }}
