# infra/helm/backend/templates/secret-db-conn.yaml
{{- if .Values.secrets.createDbConn }}
apiVersion: v1
kind: Secret
metadata:
  name: db-conn
type: Opaque
stringData:
  {{- /* Safely read from either .Values.secrets.dbConn.url or .Values.dbConn.url */ -}}
  {{- $url1 := "" -}}
  {{- if and (kindIs "map" .Values.secrets) (kindIs "map" .Values.secrets.dbConn) -}}
    {{- $url1 = (.Values.secrets.dbConn.url | default "") -}}
  {{- end -}}
  {{- $url2 := "" -}}
  {{- if kindIs "map" .Values.dbConn -}}
    {{- $url2 = (.Values.dbConn.url | default "") -}}
  {{- end -}}
  {{- $url := (default $url2 $url1) -}}
  url: {{ required "either secrets.dbConn.url or dbConn.url must be set when createDbConn=true" $url | quote }}
{{- end }}

