# infra/helm/backend/templates/secret-db-conn.yaml
{{- $vals    := .Values | default dict -}}
{{- $secrets := (get $vals "secrets") | default dict -}}
{{- $create  := (get $secrets "createDbConn") | default false -}}
{{- $hasB64  := hasKey $secrets "dbConnB64" -}}
{{- $dbConn  := (get $secrets "dbConn") | default dict -}}
{{- $raw     := (get $dbConn "url") | default "" -}}
{{- $url     := tpl ($raw | toString) . | trim -}}

{{- if and $create (or $hasB64 (ne $url "")) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-conn
  labels:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
{{- if $hasB64 }}
data:
  url: {{ (get $secrets "dbConnB64").url | toString | quote }}
{{- else }}
stringData:
  url: {{ $url | quote }}
{{- end }}
{{- end }}
