  # devops-project1/infra/helm/backend/templates/secret-db.yaml
{{- if (default false .Values.secrets.createDbCreds) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secrets.credsName | default "db-secrets" }}
  labels:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secrets.dbCredsB64.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.secrets.dbCredsB64.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbCredsB64.POSTGRES_PASSWORD | quote }}
{{- end }}
