# devops-project1/infra/helm/backend/templates/secret-db-conn.yaml
{{- if .Values.secrets.createDbConn }}

{{- $ns := .Release.Namespace -}}
{{- $dbVals := (get .Values "db") | default (dict) -}}
{{- $dbEnabled := (get $dbVals "enabled" | default false) -}}

{{- $svc := (get $dbVals "service") | default (dict) -}}
{{- $rawPort := (get $svc "port") | default 5432 -}}
{{- $svcPort := int $rawPort -}}                 {{/* <— force integer */}}
{{- $svcName := (get $svc "name") | default "db" -}}
{{- $host := printf "%s.%s.svc.cluster.local" $svcName $ns -}}

{{- $dbCreds := (get .Values.secrets "dbCreds") | default (dict) -}}
{{- $dbName := (get $dbCreds "POSTGRES_DB") | default "" -}}
{{- $dbUser := (get $dbCreds "POSTGRES_USER") | default "" -}}
{{- $dbPass := (get $dbCreds "POSTGRES_PASSWORD") | default "" -}}

{{- $explicitURL := (get .Values.secrets.dbConn "url") | default "" -}}
{{- $computedURL := "" -}}
{{- if and $dbEnabled $dbName $dbUser $dbPass -}}
  {{- $computedURL = printf "postgresql://%s:%s@%s:%d/%s?sslmode=disable" $dbUser $dbPass $host $svcPort $dbName -}}
{{- end -}}

{{- $finalURL := (default $computedURL $explicitURL) -}}
{{- if not $finalURL -}}
  {{- fail "secrets.createDbConn=true but neither secrets.dbConn.url is set nor a computable URL is available (requires db.enabled + secrets.dbCreds)." -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: db-conn
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  url: {{ $finalURL | quote }}

{{- end }}
