# infra/helm/backend/templates/secret-db-conn.yaml
{{- if and (.Values.secrets.createDbConn | default false) (.Values.secrets.dbConn.url | default "") -}}
apiVersion: v1
kind: Secret
metadata:
  name: db-conn
type: Opaque
stringData:
  url: {{ .Values.secrets.dbConn.url | quote }}
{{- end }}
