# infra/helm/backend/templates/secret-db-conn.yaml
{{- /* Safe lookups: never assume types */ -}}
{{- $vals := .Values | default dict -}}
{{- $secrets := (get $vals "secrets") | default dict -}}
{{- $create := (get $secrets "createDbConn") | default false -}}
{{- $dbConn := (get $secrets "dbConn") | default dict -}}
{{- $raw := (get $dbConn "url") | default "" -}}
{{- $url := tpl ($raw | toString) . | trim -}}

{{- if and $create (ne $url "") -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-conn
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  url: {{ $url | quote }}
{{- end -}}
