# infra/helm/backend/templates/secret-db-conn.yaml
{{- $raw := dig "secrets" "dbConn" "url" .Values "" -}}
{{- $url := (tpl $raw . | trim) -}}
{{- if and (default false .Values.secrets.createDbConn) (ne $url "") -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-conn
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  url: {{ $url | quote }}
{{- end }}
