# infra/helm/backend/templates/secret-db-conn.yaml
{{- $url := "" -}}
{{- if and .Values.secrets .Values.secrets.dbConn .Values.secrets.dbConn.url -}}
  {{- $url = tpl .Values.secrets.dbConn.url . | trim -}}
{{- end -}}
{{- if and (default false .Values.secrets.createDbConn) (ne $url "") }}
apiVersion: v1
kind: Secret
metadata:
  name: db-conn
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  url: {{ $url | quote }}
{{- end }}

