  # devops-project1/infra/helm/backend/templates/secret-db.yaml
{{- if (.Values.secrets.createDbCreds | default false) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secrets.credsName | default "db-secrets" }}
  labels:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.dbCreds.POSTGRES_DB | default "mario" | quote }}
  POSTGRES_USER: {{ .Values.secrets.dbCreds.POSTGRES_USER | default "mario" | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbCreds.POSTGRES_PASSWORD | default "mario123" | quote }}
{{- end }}


