  # devops-project1/infra/helm/backend/templates/secret-db.yaml
{{- if .Values.secrets.createDbCreds }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secrets.credsName | default "db-secrets" }}
type: Opaque
stringData:
  POSTGRES_DB: {{ required "secrets.dbCreds.POSTGRES_DB required" .Values.secrets.dbCreds.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ required "secrets.dbCreds.POSTGRES_USER required" .Values.secrets.dbCreds.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ required "secrets.dbCreds.POSTGRES_PASSWORD required" .Values.secrets.dbCreds.POSTGRES_PASSWORD | quote }}
{{- end }}


