# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector: { app: mario-app }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
