# devops-project1/infra/helm/backend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
spec.selector:
  app.kubernetes.io/name: backend
  app.kubernetes.io/instance: backend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}


