# devops-project1/infra/helm/backend/templates/service.yaml
{{- $name := default .Chart.Name .Values.nameOverride -}}
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name | default "backend" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

