image:
  repository: docker.io/itaef/supermario-front
  tag: ""                    # empty → uses .Chart.AppVersion
  pullPolicy: IfNotPresent

service:
  name: web-svc
  port: 80

# optional extra env for the container
env: []

# resources live under a single resources: block
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

replicas: 1

ingress:
  enabled: true
  host: web.mario.local
  path: /
  ingressClassName: nginx
