global:
  repoURL: https://github.com/tAIness/devops-project1.git
  rootPath: infra/k8s
  destinationNamespace: argocd

project:
  enabled: true
  name: default
  description: Default Argo CD project
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist: []

apps:
  - name: web
    path: web
    targetRevision: ""     # empty => uses Chart.appVersion
  - name: backend
    path: backend
    targetRevision: ""     # empty => uses Chart.appVersion
