{{- /* Create namespaces if you want the chart to own them */ -}}
{{- $ns := list "mario-backend" "mario-web" "monitoring" -}}
{{- range $n := $ns }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $n }}
  labels:
    app.kubernetes.io/managed-by: Helm
---
{{- end }}
