{{- if (.Values.project.enabled | default false) }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project.name | default "default" }}
  namespace: {{ .Values.global.argoNamespace | default "argocd" }}
spec:
  description: "Local project"
  sourceRepos: ["*"]
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
{{- end }}
