{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    # ensure this secret is applied before the Application (default wave 0)
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
{{- range $k, $v := .stringData }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
---
{{- end }}
