{{- range $s := .Values.secrets | default (list) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $s.name }}
  namespace: {{ $s.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
{{- range $k, $v := $s.stringData }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
---
{{- end }}
