services:
  db:
    image: postgres:15
    platform: linux/arm64
    container_name: supermario_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-mario}
      POSTGRES_USER: ${DB_USER:-mario}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mario123}
    volumes:
      - supermario_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-mario} -d ${DB_NAME:-mario}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: ${DOCKERHUB_REPO_APP}:${TAG}
    pull_policy: never
    container_name: supermario_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # IMPORTANT: inside the compose network Postgres is always on 5432
      DB_URL: postgresql://${DB_USER:-mario}:${DB_PASSWORD:-mario123}@db:5432/${DB_NAME:-mario}?sslmode=disable
      FLASK_PORT: ${FLASK_PORT:-8000}
    ports:
      - "${FLASK_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${FLASK_PORT:-8000}/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 40

  web:
    image: ${DOCKERHUB_REPO_WEB}:${TAG}
    pull_policy: never
    container_name: supermario_web
    depends_on:
      app:
        condition: service_healthy
    environment:
      BACKEND_URL: "http://app:${FLASK_PORT:-8000}"
    ports:
      - "${WEB_PORT:-8080}:80"

volumes:
  supermario_db_data: {}
