name: Auto patch tag
on:
  push:
    branches:
      - main
permissions:
  contents: write
concurrency:
  group: auto-patch-${{ github.ref }}
  cancel-in-progress: false

jobs:
  cut:
    uses: ./.github/workflows/_cut-tag.yml
    with:
      bump: patch
      prefix: v
      initial_version: 1.0.0
      create_github_release: true
