name: CI (PR checks)

on:
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
        cache-dependency-path: app/requirements.txt

    - name: Install deps for lint
      run: |
        python -m pip install -U pip
        pip install -r app/requirements.txt pylint

    - name: Run pylint (in app/)
      working-directory: app
      # relax docstring rules for now; remove disables when ready
      run: python -m pylint --disable=C0114,C0116 *.py

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
        cache-dependency-path: |
         app/requirements.txt
         app/tests/requirements.txt

    - name: Install deps
      run: |
        python -m pip install -U pip
        pip install -r app/requirements.txt
        if [ -f app/tests/requirements.txt ]; then pip install -r app/tests/requirements.txt; fi

    - name: Run unit tests
      working-directory: app
      run: python -m pytest -q --junitxml=pytest-results.xml

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: app/pytest-results.xml

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - name: Build app image (no push on PR)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: app/Dockerfile
        push: false
        tags: local/app:pr-check

    - name: Build web image (no push on PR)
      uses: docker/build-push-action@v6
      with:
        context: web
        file: web/Dockerfile
        push: false
        tags: local/web:pr-check

snyk-pr:
  uses: tAIness/devops-ci-lib/.github/workflows/snyk-reusable.yml@main
  secrets: inherit
  with:
    dockerfiles: |
      app/Dockerfile
      web/Dockerfile
    ignore_list_path: security/ignores.txt
    severity: high
    upload_artifacts: true
