name: CI (PR checks)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'web/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            app/requirements.txt
            app/tests/requirements.txt

      - name: Install deps
        run: |
          pip install -r app/requirements.txt
          if [ -f app/tests/requirements.txt ]; then pip install -r app/tests/requirements.txt; fi

      - name: Run unit tests
        working-directory: app
        run: python -m pytest -q --junitxml=pytest-results.xml

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: app/pytest-results.xml
