name: Cut release tag (manual)
on:
  workflow_dispatch:
    inputs:
      bump:
        description: patch | minor | major
        type: choice
        required: true
        options:
          - patch
          - minor
          - major
permissions:
  contents: write

jobs:
  cut:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cut tag
        uses: ./.github/workflows/_cut-tag.yml   # or your reusable
        with:
          bump: ${{ github.event.inputs.bump }}
          prefix: v
          initial_version: 1.0.0
          create_github_release: true
