name: Cut release tag
on:
  workflow_dispatch:
    inputs:
      bump:
        description: patch | minor | major
        type: choice
        required: true
        default: patch
        options:
        - patch
        - minor
        - major

permissions:
  contents: write

jobs:
  cut:
    uses: tAIness/devops-ci-lib/.github/workflows/cut-tag.yml@v1.1.0
    with:
      bump: ${{ github.event.inputs.bump }}
      prefix: v
      initial_version: 1.0.0
      create_github_release: true
