name: Web smoke (Compose)
on:
  workflow_call:
    inputs:
      service:       { type: string,  default: "front" }
      url:           { type: string,  default: "http://localhost:8080/" }
      asserts:       { type: string,  default: "" }   # newline-separated substrings
      link_check:    { type: boolean, default: true }
      lychee_config: { type: string,  default: ".lychee.toml" }

permissions: read-all

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker compose build ${{ inputs.service }}

      - name: Run service
        run: docker compose up -d ${{ inputs.service }}

      - name: Wait for service
        run: |
          for i in {1..60}; do
            if curl -fsS "${{ inputs.url }}" >/dev/null; then exit 0; fi
            sleep 1
          done
          echo "service did not start"; exit 1

      - name: Assert content
        run: |
          curl -fsS "${{ inputs.url }}" -o page.html
          while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            echo "assert: $line"
            grep -q "$line" page.html
          done <<< "${{ inputs.asserts }}"

      - name: Link checker (lychee)
        if: ${{ inputs.link_check }}
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config ${{ inputs.lychee_config }} page.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tear down
        if: always()
        run: docker compose down -v
