name: PR - CI
on:
  pull_request:
    branches:
      - main
      - master
permissions: read-all

jobs:
  validate:
    uses: tAIness/devops-ci-lib/.github/workflows/validate.yml@v1.1.4
    with:
      yamllint_strict: false

  python:
    needs:
      - validate
    uses: tAIness/devops-ci-lib/.github/workflows/python-tests.yml@v1.1.1
    with:
      workdir: app
      python_version: "3.11"

  web-smoke:
    needs:
      - validate
    uses: tAIness/devops-ci-lib/.github/workflows/web-smoke.yml@v1.1.3
    with:
      service: front
      url: http://localhost:8080/
      asserts: |
        Play Super Mario
        Gallery
        Nintendo Shop
      link_check: true
      lychee_config: .lychee.toml

  e2e:
    needs:
      - web-smoke
    uses: tAIness/devops-ci-lib/.github/workflows/playwright-e2e.yml@v1.1.2
    with:
      node_version: "20"
      base_url: http://localhost:8080
      compose_service: front
      test_command: npm run test:e2e
