name: semver-decide
on:
  workflow_call:
    inputs:
      prefix:
        type: string
        default: "v"
      initial_version:
        type: string
        default: "1.0.0"
      force_bump:
        type: string
        default: ""          # "", "patch", "minor", "major"
    outputs:
      bump:
        description: "Calculated bump"
        value: ${{ jobs.decide.outputs.bump }}

permissions: read-all

jobs:
  decide:
    runs-on: ubuntu-latest
    outputs:
      bump: ${{ steps.choose.outputs.bump }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Determine last tag
        id: last
        shell: bash
        run: |
          set -euo pipefail
          prefix="${{ inputs.prefix }}"
          last="$(git tag -l "${prefix}[0-9]*.[0-9]*.[0-9]*" --sort=-v:refname | head -n1 || true)"
          echo "last=$last" >> "$GITHUB_OUTPUT"

      - name: Choose bump
        id: choose
        shell: bash
        run: |
          set -euo pipefail
          force="${{ inputs.force_bump }}"
          if [[ -n "$force" ]]; then
            echo "bump=$force" >> "$GITHUB_OUTPUT"
            echo "Forced bump: $force"
            exit 0
          fi

          last="${{ steps.last.outputs.last }}"
          range=""
          if [[ -n "$last" ]]; then range="${last}..HEAD"; fi

          log="$(git log --no-merges --pretty=format:'%s%n%b%n---' $range || true)"

          bump="patch"
          if echo "$log" | grep -Eiq '^.*!:|(^|[[:space:]])BREAKING CHANGE([[:space:]]|:)'; then
            bump="major"
          elif echo "$log" | grep -Eq '^feat(\(.+\))?:'; then
            bump="minor"
          fi

          echo "bump=$bump" >> "$GITHUB_OUTPUT"
          echo "Auto bump: $bump"
