name: PR - Ping
on:
  pull_request:
    branches:
      - main
      - master
permissions: read-all

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "pong from devops-ci-lib"
      # If you had this (yamllint hates spaces inside braces):
      # - uses: reviewdog/action-actionlint@v1
      #   with: { fail_on_error: true }
      # Replace with:
      - name: actionlint (example)
        uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
