name: PR - Security
on:
  pull_request:
    branches:
    - main
    - master
permissions: read-all

jobs:
  deps:
    uses: tAIness/devops-ci-lib/.github/workflows/security.yml@v1.1.6
    with:
      mode: deps
      soft_fail: true       # don't fail PRs; report only
