name: PR - Validate
on:
  pull_request:
    branches:
    - main
    - master
permissions: read-all

jobs:
  validate:
    uses: tAIness/devops-ci-lib/.github/workflows/validate.yml@v1.1.5
    with:
      yamllint_strict: false
