name: Security - Nightly
on:
  schedule:
    - cron: '0 2 * * *'
permissions: read-all

jobs:
  security:
    uses: tAIness/devops-ci-lib/.github/workflows/security.yml@v1.0.0
    with:
      scan_deps: true
      scan_images: false
      severity: medium
      soft_fail: false
    secrets: inherit
