name: Security - Nightly
on:
  schedule:
    - cron: '0 2 * * *'
permissions: read-all

jobs:
  deps:
    uses: tAIness/devops-ci-lib/.github/workflows/security.yml@v1.1.6
    with:
      mode: deps
      soft_fail: false
